# pull official base image
FROM python:3.12-slim as base

ENV VIRTUAL_ENV=/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# install dependencies
RUN pip3 install --upgrade pip
COPY ./requirements/ ./requirements/
RUN pip3 install -r requirements/development.txt


FROM python:3.12
COPY --from=base /venv /venv

# set environment variables
ENV PATH="/venv/bin:$PATH"

WORKDIR /app
CMD ["./entrypoint.sh", "dev"]
